
version: '2'
services:
    data-app:
        image: ramazanfirin/countbuddyftp-master
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger,no-liquibase
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:admin@ec2-3-15-135-106.us-east-2.compute.amazonaws.com:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@ec2-3-15-135-106.us-east-2.compute.amazonaws.com:8761/config
            - JHIPSTER_REGISTRY_PASSWORD=admin
            - JAVA_OPTS=-Xmx2048m
            - SPRING_DATASOURCE_URL=jdbc:mysql://mastertekdb.cfyototaodfv.us-east-2.rds.amazonaws.com:3306/countbuddy_new_test?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATASOURCE_USERNAME=masterTek6634
            - SPRING_DATASOURCE_PASSWORD=105957Grk.
            #- SERVER_PORT=9096
            - application_ftpDirectory=/home/ramazan/publicDirectory
            - application_passowordFile=/home/ramazan/myftpusers.properties
            - application_ftpPort=21
        ports:
            - 8086:8080
            - 21:21
        volumes:
            - $HOME/Documents:/home/ramazan/


